version: "3.9"

x-common-variables: &common-variables
  MYSQL_DATABASE: todo_app
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/0_db.sql
    ports:
     - "3307:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost
   
    

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build: ./backend
    depends_on:
      - mysql_db
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db

  client:
   stdin_open: true
   environment:
      - CHOKIDAR_USEPOLLING=true
   build: ./frontend
   ports:
      - 3000:3000
   volumes:
      - ./frontend:/app
      - /app/node_modules
 
  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8000:8080
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db
